version: '3.4'

services:
  insightderm.host.api:
    image: ${DOCKER_REGISTRY}insightdermhostapi
    build:
      context: .
      dockerfile: InsightDerm.Host.Api/Dockerfile
    environment:
     - ASPNETCORE_URLS http://*:5001
     - ASPNETCORE_ENVIRONMENT Production
    ports:
      - "5001:80"